-- =========================================================
-- Clean schema.sql (PostgreSQL)
-- Recreates schema + tables + constraints + indexes
-- =========================================================

CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION pg_database_owner;
COMMENT ON SCHEMA public IS 'standard public schema';

-- =========================================================
-- Base tables (no FKs)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.articles_raw (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source" text NOT NULL,
  media_type text NOT NULL,
  feed_name text NOT NULL,
  title text NOT NULL,
  summary text NULL,
  url text NOT NULL UNIQUE,
  published_at timestamp NULL,
  inserted_at timestamp NOT NULL DEFAULT now(),
  raw_content text NULL
);

CREATE INDEX IF NOT EXISTS idx_articles_raw_published_source
  ON public.articles_raw USING btree (published_at, source, media_type);

CREATE TABLE IF NOT EXISTS public.articles_raw_f24 (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source" text NOT NULL,
  lang text NOT NULL,
  media_type text NOT NULL,
  feed_name text NOT NULL,
  title text NOT NULL,
  summary text NULL,
  url text NOT NULL UNIQUE,
  published_at timestamp NULL,
  inserted_at timestamp NOT NULL DEFAULT now(),
  raw_content text NULL
);

CREATE TABLE IF NOT EXISTS public.keyword_lifetime (
  word text NULL,
  start_date date NULL,
  end_date date NULL,
  duration_days int4 NULL,
  total_frequency int4 NULL
);

CREATE TABLE IF NOT EXISTS public.keywords_daily (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "source" text NOT NULL,
  media_type text NOT NULL,
  word text NOT NULL,
  count int4 NOT NULL,
  "rank" int4 NOT NULL,
  CONSTRAINT keywords_daily_date_source_media_type_word_key
    UNIQUE (date, source, media_type, word)
);

CREATE INDEX IF NOT EXISTS idx_keywords_daily_date_source_media
  ON public.keywords_daily USING btree (date, source, media_type);

CREATE TABLE IF NOT EXISTS public.keywords_daily_f24 (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "source" text NOT NULL,
  lang text NOT NULL,
  word text NOT NULL,
  count int4 NOT NULL,
  "rank" int4 NOT NULL,
  CONSTRAINT keywords_daily_f24_unique UNIQUE (date, source, lang, word),
  CONSTRAINT keywords_daily_f24_date_source_word_key UNIQUE (date, source, word)
);

CREATE TABLE IF NOT EXISTS public.media_bias_scores (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "source" text NOT NULL,
  theme text NOT NULL,
  bias_score float4 NOT NULL,
  methodology text NULL,
  details jsonb NULL
);

CREATE TABLE IF NOT EXISTS public.narratives_clusters (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cluster_id int4 NOT NULL,
  "label" text NULL,
  top_keywords _text NULL,
  "size" int4 NOT NULL,
  created_at timestamptz NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.narratives_comparison (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  topic_id int4 NOT NULL,
  source_a text NOT NULL,
  source_b text NOT NULL,
  similarity float4 NOT NULL,
  details jsonb NULL
);

CREATE TABLE IF NOT EXISTS public.spikes (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  topic_id int4 NOT NULL,
  "source" text NOT NULL,
  spike_score float4 NOT NULL,
  baseline_window int4 NOT NULL,
  details jsonb NULL
);

CREATE TABLE IF NOT EXISTS public.theme_lifetime (
  theme text NULL,
  start_date date NULL,
  end_date date NULL,
  peak_date date NULL,
  total_mentions int4 NULL
);

CREATE TABLE IF NOT EXISTS public.topic_lifetime (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id int4 NOT NULL,
  topic_label text NULL,
  first_seen_date date NOT NULL,
  last_seen_date date NOT NULL,
  peak_date date NULL,
  total_mentions int4 NOT NULL,
  sources_covered _text NULL
);

CREATE TABLE IF NOT EXISTS public.topics_daily (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "source" text NOT NULL,
  media_type text NOT NULL,
  topic_id int4 NOT NULL,
  topic_label text NULL,
  articles_count int4 NOT NULL,
  keywords _text NULL,
  CONSTRAINT topics_daily_date_source_media_type_topic_id_key
    UNIQUE (date, source, media_type, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_topics_daily_date_source_media
  ON public.topics_daily USING btree (date, source, media_type);

CREATE TABLE IF NOT EXISTS public.topics_daily_f24 (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "source" text NOT NULL,
  lang text NOT NULL,
  topic_id int4 NOT NULL,
  topic_label text NULL,
  articles_count int4 NOT NULL,
  keywords _text NULL,
  CONSTRAINT topics_daily_f24_unique UNIQUE (date, source, lang, topic_id),
  CONSTRAINT topics_daily_f24_date_source_lang_topic_id_key UNIQUE (date, source, lang, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_topics_daily_f24_date
  ON public.topics_daily_f24 USING btree (date);
CREATE INDEX IF NOT EXISTS idx_topics_daily_f24_lang
  ON public.topics_daily_f24 USING btree (lang);
CREATE INDEX IF NOT EXISTS idx_topics_daily_f24_source
  ON public.topics_daily_f24 USING btree (source);

-- =========================================================
-- Dependent tables (FKs)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.articles_clean (
  article_id int4 PRIMARY KEY,
  cleaned_text text NOT NULL,
  tokens _text NULL,
  lemmas _text NULL,
  lang text NULL DEFAULT 'fr'::text,
  entities jsonb NULL,
  CONSTRAINT articles_clean_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.articles_raw(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.articles_clean_f24 (
  article_id int4 PRIMARY KEY,
  cleaned_text text NOT NULL,
  tokens _text NULL,
  lemmas _text NULL,
  lang text NOT NULL,
  entities jsonb NULL,
  CONSTRAINT articles_clean_f24_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.articles_raw_f24(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.narratives_assignments (
  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id int4 NOT NULL,
  cluster_id int4 NOT NULL,
  score float4 NULL,
  created_at timestamptz NULL DEFAULT now(),
  CONSTRAINT narratives_assignments_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.articles_raw(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_narratives_article_cluster
  ON public.narratives_assignments USING btree (article_id, cluster_id);
CREATE INDEX IF NOT EXISTS idx_narratives_assignments_article
  ON public.narratives_assignments USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_narratives_assignments_cluster
  ON public.narratives_assignments USING btree (cluster_id);


-- 1) Raw social posts (public signals only)
CREATE TABLE IF NOT EXISTS social_posts_raw (
  id BIGSERIAL PRIMARY KEY,
  platform TEXT NOT NULL,           -- reddit | mastodon | youtube | tiktok
  source TEXT NOT NULL,             -- subreddit | instance | channel | query
  external_id TEXT NOT NULL,        -- post_id / toot_id / video_id
  url TEXT,
  title TEXT,
  content TEXT,
  author TEXT,
  published_at TIMESTAMP,
  lang_guess TEXT,
  raw_json JSONB,
  inserted_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (platform, external_id)
);

CREATE INDEX IF NOT EXISTS idx_social_raw_platform_date
ON social_posts_raw(platform, published_at);

-- 2) Clean social posts
CREATE TABLE IF NOT EXISTS social_posts_clean (
  id BIGSERIAL PRIMARY KEY,
  platform TEXT NOT NULL,
  source TEXT NOT NULL,
  external_id TEXT NOT NULL,
  url TEXT,
  title TEXT,
  clean_text TEXT,
  lang TEXT,
  tokens JSONB,
  lemmas JSONB,
  entities JSONB,
  hashtags JSONB,
  processed_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (platform, external_id)
);

CREATE INDEX IF NOT EXISTS idx_social_clean_lang_date
ON social_posts_clean(lang, processed_at);

-- 3) Daily keywords (social)
CREATE TABLE IF NOT EXISTS social_keywords_daily (
  id BIGSERIAL PRIMARY KEY,
  date DATE NOT NULL,
  platform TEXT NOT NULL,
  source TEXT NOT NULL,
  lang TEXT NOT NULL,
  keyword TEXT NOT NULL,
  score DOUBLE PRECISION,
  n_docs INT,
  UNIQUE (date, platform, source, lang, keyword)
);

-- 4) Daily topics (social)
CREATE TABLE IF NOT EXISTS social_topics_daily (
  id BIGSERIAL PRIMARY KEY,
  date DATE NOT NULL,
  platform TEXT NOT NULL,
  source TEXT NOT NULL,
  lang TEXT NOT NULL,
  topic_id INT NOT NULL,
  top_terms JSONB,
  weight DOUBLE PRECISION,
  n_docs INT,
  UNIQUE (date, platform, source, lang, topic_id)
);
